products = [
    {
        "bracelet": None,
        "brand": "PDPAOLA",
        "caja": None,
        "category": "anillo",
        "clasp": None,
        "coating": "rodio",
        "description": "Anillo solitario de plata de primera ley con circonita.",
        "earring_type": None,
        "gem": "Circonita",
        "gender": "mujer",
        "id": 8,
        "metal": "plata de primera ley",
        "name": "Anillo solitario plata circonita",
        "price": 49.9,
        "ring_type": "Anillo Solitario",
        "url_image": "https://cdn.palbincdn.com/users/50822/images/12182-anillo-solitario-plata-1698927548-1707780008.jpg",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 20,
    },
    {
        "bracelet": None,
        "brand": "Tous",
        "caja": None,
        "category": "anillo",
        "clasp": None,
        "coating": "oro amarillo 18k",
        "description": "Alianza clásica en oro amarillo de 18k.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "mujer",
        "id": 9,
        "metal": "oro amarillo 18k",
        "name": "Anillo alianza oro 18k",
        "price": 299.0,
        "ring_type": "Anillo Alianza",
        "url_image": "https://i.pinimg.com/1200x/c5/66/a9/c566a96f11491dee475a9275a3749900.jpg",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 10,
    },
    {
        "bracelet": None,
        "brand": "Versace",
        "caja": None,
        "category": "anillo",
        "clasp": None,
        "coating": "rodio",
        "description": "Anillo con gema central esmeralda y baño de rodio.",
        "earring_type": None,
        "gem": "Esmeralda",
        "gender": "mujer",
        "id": 10,
        "metal": "oro blanco 18 k",
        "name": "Anillo con esmeralda oro blanco",
        "price": 599.0,
        "ring_type": "Anillo Con gemas",
        "url_image": "https://i.pinimg.com/1200x/7a/60/43/7a6043359ca67b17f5a90b2594880d4a.jpg",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 5,
    },
    {
        "bracelet": None,
        "brand": "Guess",
        "caja": None,
        "category": "anillo",
        "clasp": None,
        "coating": "oro rosa 18k",
        "description": "Anillo anillo solitario en oro amarillo 18k con acabado oro rosa 18k.",
        "earring_type": None,
        "gem": "Perla cultivada",
        "gender": "hombre",
        "id": 23,
        "metal": "oro amarillo 18k",
        "name": "Anillo Solitario Guess 4",
        "price": 62.1,
        "ring_type": "Anillo Solitario",
        "url_image": "https://source.unsplash.com/featured/?ring,Guess,Perla%20cultivada",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 17,
    },
    {
        "bracelet": None,
        "brand": "Tous",
        "caja": None,
        "category": "anillo",
        "clasp": None,
        "coating": None,
        "description": "Anillo anillo solitario en oro blanco 18k con acabado pulido.",
        "earring_type": None,
        "gem": "Rubí",
        "gender": "mujer",
        "id": 24,
        "metal": "oro blanco 18k",
        "name": "Anillo Solitario Tous 5",
        "price": 69.6,
        "ring_type": "Anillo Solitario",
        "url_image": "https://source.unsplash.com/featured/?ring,Tous,Rubí",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 20,
    },
    {
        "bracelet": None,
        "brand": "Viceroy",
        "caja": None,
        "category": "anillo",
        "clasp": None,
        "coating": "rodio",
        "description": "Anillo anillo solitario en plata de primera ley con acabado rodio.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "hombre",
        "id": 25,
        "metal": "plata de primera ley",
        "name": "Anillo Solitario Viceroy 6",
        "price": 77.4,
        "ring_type": "Anillo Solitario",
        "url_image": "https://source.unsplash.com/featured/?ring,Viceroy,Sin%20gema",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 23,
    },
    {
        "bracelet": None,
        "brand": "Tous",
        "caja": None,
        "category": "anillo",
        "clasp": None,
        "coating": None,
        "description": "Anillo anillo solitario en oro amarillo 18k con acabado pulido.",
        "earring_type": None,
        "gem": "Rubí",
        "gender": "hombre",
        "id": 26,
        "metal": "oro amarillo 18k",
        "name": "Anillo Solitario Tous 7",
        "price": 84.8,
        "ring_type": "Anillo Solitario",
        "url_image": "https://source.unsplash.com/featured/?ring,Tous,Rubí",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 26,
    },
    {
        "bracelet": None,
        "brand": "PDPAOLA",
        "caja": None,
        "category": "anillo",
        "clasp": None,
        "coating": "oro amarillo 18k",
        "description": "Anillo anillo band en oro amarillo 18k con acabado oro amarillo 18k.",
        "earring_type": None,
        "gem": "Zafiro",
        "gender": "mujer",
        "id": 27,
        "metal": "oro amarillo 18k",
        "name": "Anillo Band PDPAOLA 8",
        "price": 91.8,
        "ring_type": "Anillo Band",
        "url_image": "https://source.unsplash.com/featured/?ring,PDPAOLA,Zafiro",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 29,
    },
    {
        "bracelet": None,
        "brand": "Aristocrazy",
        "caja": None,
        "category": "anillo",
        "clasp": None,
        "coating": None,
        "description": "Anillo anillo con gemas en oro amarillo 18k con acabado pulido.",
        "earring_type": None,
        "gem": "Rubí",
        "gender": "mujer",
        "id": 28,
        "metal": "oro amarillo 18k",
        "name": "Anillo Con gemas Aristocrazy 9",
        "price": 99.2,
        "ring_type": "Anillo Con gemas",
        "url_image": "https://source.unsplash.com/featured/?ring,Aristocrazy,Rubí",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 32,
    },
    {
        "bracelet": None,
        "brand": "Tous",
        "caja": None,
        "category": "anillo",
        "clasp": None,
        "coating": "rodio",
        "description": "Anillo anillo con gemas en plata de primera ley con acabado rodio.",
        "earring_type": None,
        "gem": "Zafiro",
        "gender": "mujer",
        "id": 29,
        "metal": "plata de primera ley",
        "name": "Anillo Con gemas Tous 10",
        "price": 107.0,
        "ring_type": "Anillo Con gemas",
        "url_image": "https://source.unsplash.com/featured/?ring,Tous,Zafiro",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 35,
    },
    {
        "bracelet": None,
        "brand": "Pandora",
        "caja": None,
        "category": "anillo",
        "clasp": None,
        "coating": "oro amarillo 18k",
        "description": "Anillo anillo alianza en oro blanco 18k con acabado oro amarillo 18k.",
        "earring_type": None,
        "gem": "Circonita",
        "gender": "mujer",
        "id": 30,
        "metal": "oro blanco 18k",
        "name": "Anillo Alianza Pandora 11",
        "price": 114.0,
        "ring_type": "Anillo Alianza",
        "url_image": "https://source.unsplash.com/featured/?ring,Pandora,Circonita",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 38,
    },
    {
        "bracelet": None,
        "brand": "Aristocrazy",
        "caja": None,
        "category": "anillo",
        "clasp": None,
        "coating": "oro amarillo 18k",
        "description": "Anillo anillo con gemas en acero con acabado oro amarillo 18k.",
        "earring_type": None,
        "gem": "Perla cultivada",
        "gender": "mujer",
        "id": 31,
        "metal": "acero",
        "name": "Anillo Con gemas Aristocrazy 12",
        "price": 121.8,
        "ring_type": "Anillo Con gemas",
        "url_image": "https://source.unsplash.com/featured/?ring,Aristocrazy,Perla%20cultivada",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 41,
    },
    {
        "bracelet": None,
        "brand": "Tous",
        "caja": None,
        "category": "anillo",
        "clasp": None,
        "coating": "oro rosa 18k",
        "description": "Anillo anillo alianza en plata de primera ley con acabado oro rosa 18k.",
        "earring_type": None,
        "gem": "Circonita",
        "gender": "hombre",
        "id": 32,
        "metal": "plata de primera ley",
        "name": "Anillo Alianza Tous 13",
        "price": 128.9,
        "ring_type": "Anillo Alianza",
        "url_image": "https://source.unsplash.com/featured/?ring,Tous,Circonita",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 44,
    },
    {
        "bracelet": None,
        "brand": "Viceroy",
        "caja": None,
        "category": "anillo",
        "clasp": None,
        "coating": None,
        "description": "Anillo anillo con gemas en plata de primera ley con acabado pulido.",
        "earring_type": None,
        "gem": "Amatista",
        "gender": "mujer",
        "id": 33,
        "metal": "plata de primera ley",
        "name": "Anillo Con gemas Viceroy 14",
        "price": 136.3,
        "ring_type": "Anillo Con gemas",
        "url_image": "https://source.unsplash.com/featured/?ring,Viceroy,Amatista",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 47,
    },
    {
        "bracelet": None,
        "brand": "Luxenter",
        "caja": None,
        "category": "anillo",
        "clasp": None,
        "coating": "oro rosa 18k",
        "description": "Anillo anillo con gemas en acero con acabado oro rosa 18k.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "mujer",
        "id": 34,
        "metal": "acero",
        "name": "Anillo Con gemas Luxenter 15",
        "price": 143.5,
        "ring_type": "Anillo Con gemas",
        "url_image": "https://source.unsplash.com/featured/?ring,Luxenter,Sin%20gema",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 50,
    },
    {
        "bracelet": None,
        "brand": "Tous",
        "caja": None,
        "category": "anillo",
        "clasp": None,
        "coating": "oro amarillo 18k",
        "description": "Anillo anillo con gemas en plata de primera ley con acabado oro amarillo 18k.",
        "earring_type": None,
        "gem": "Perla cultivada",
        "gender": "hombre",
        "id": 35,
        "metal": "plata de primera ley",
        "name": "Anillo Con gemas Tous 16",
        "price": 151.4,
        "ring_type": "Anillo Con gemas",
        "url_image": "https://source.unsplash.com/featured/?ring,Tous,Perla%20cultivada",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 53,
    },
    {
        "bracelet": None,
        "brand": "Guess",
        "caja": None,
        "category": "anillo",
        "clasp": None,
        "coating": "oro rosa 18k",
        "description": "Anillo anillo band en plata de primera ley con acabado oro rosa 18k.",
        "earring_type": None,
        "gem": "Esmeralda",
        "gender": "mujer",
        "id": 36,
        "metal": "plata de primera ley",
        "name": "Anillo Band Guess 17",
        "price": 158.4,
        "ring_type": "Anillo Band",
        "url_image": "https://source.unsplash.com/featured/?ring,Guess,Esmeralda",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 56,
    },
    {
        "bracelet": None,
        "brand": "PDPAOLA",
        "caja": None,
        "category": "anillo",
        "clasp": None,
        "coating": "oro amarillo 18k",
        "description": "Anillo anillo midi en oro amarillo 18k con acabado oro amarillo 18k.",
        "earring_type": None,
        "gem": "Circonita",
        "gender": "mujer",
        "id": 37,
        "metal": "oro amarillo 18k",
        "name": "Anillo Midi PDPAOLA 18",
        "price": 165.8,
        "ring_type": "Anillo Midi",
        "url_image": "https://source.unsplash.com/featured/?ring,PDPAOLA,Circonita",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 59,
    },
    {
        "bracelet": None,
        "brand": "Pandora",
        "caja": None,
        "category": "anillo",
        "clasp": None,
        "coating": "rodio",
        "description": "Anillo anillo band en plata de primera ley con acabado rodio.",
        "earring_type": None,
        "gem": "Zafiro",
        "gender": "mujer",
        "id": 38,
        "metal": "plata de primera ley",
        "name": "Anillo Band Pandora 19",
        "price": 173.6,
        "ring_type": "Anillo Band",
        "url_image": "https://source.unsplash.com/featured/?ring,Pandora,Zafiro",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 62,
    },
    {
        "bracelet": None,
        "brand": "Swarovski",
        "caja": None,
        "category": "anillo",
        "clasp": None,
        "coating": "oro amarillo 18k",
        "description": "Anillo anillo con gemas en acero con acabado oro amarillo 18k.",
        "earring_type": None,
        "gem": "Perla cultivada",
        "gender": "mujer",
        "id": 39,
        "metal": "acero",
        "name": "Anillo Con gemas Swarovski 20",
        "price": 181.0,
        "ring_type": "Anillo Con gemas",
        "url_image": "https://source.unsplash.com/featured/?ring,Swarovski,Perla%20cultivada",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 65,
    },
    {
        "bracelet": None,
        "brand": "Viceroy",
        "caja": None,
        "category": "anillo",
        "clasp": None,
        "coating": "rodio",
        "description": "Anillo anillo alianza en oro amarillo 18k con acabado rodio.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "mujer",
        "id": 40,
        "metal": "oro amarillo 18k",
        "name": "Anillo Alianza Viceroy 21",
        "price": 188.0,
        "ring_type": "Anillo Alianza",
        "url_image": "https://source.unsplash.com/featured/?ring,Viceroy,Sin%20gema",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 8,
    },
    {
        "bracelet": None,
        "brand": "Agatha",
        "caja": None,
        "category": "anillo",
        "clasp": None,
        "coating": "oro rosa 18k",
        "description": "Anillo anillo con gemas en plata de primera ley con acabado oro rosa 18k.",
        "earring_type": None,
        "gem": "Amatista",
        "gender": "mujer",
        "id": 41,
        "metal": "plata de primera ley",
        "name": "Anillo Con gemas Agatha 22",
        "price": 195.4,
        "ring_type": "Anillo Con gemas",
        "url_image": "https://source.unsplash.com/featured/?ring,Agatha,Amatista",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 11,
    },
    {
        "bracelet": None,
        "brand": "Swarovski",
        "caja": None,
        "category": "anillo",
        "clasp": None,
        "coating": "oro amarillo 18k",
        "description": "Anillo anillo alianza en acero con acabado oro amarillo 18k.",
        "earring_type": None,
        "gem": "Rubí",
        "gender": "mujer",
        "id": 42,
        "metal": "acero",
        "name": "Anillo Alianza Swarovski 23",
        "price": 202.9,
        "ring_type": "Anillo Alianza",
        "url_image": "https://source.unsplash.com/featured/?ring,Swarovski,Rubí",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 14,
    },
    {
        "bracelet": None,
        "brand": "Thomas Sabo",
        "caja": None,
        "category": "anillo",
        "clasp": None,
        "coating": "oro rosa 18k",
        "description": "Anillo anillo midi en plata de primera ley con acabado oro rosa 18k.",
        "earring_type": None,
        "gem": "Amatista",
        "gender": "mujer",
        "id": 43,
        "metal": "plata de primera ley",
        "name": "Anillo Midi Thomas Sabo 24",
        "price": 210.6,
        "ring_type": "Anillo Midi",
        "url_image": "https://source.unsplash.com/featured/?ring,Thomas%20Sabo,Amatista",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 17,
    },
    {
        "bracelet": None,
        "brand": "Tous",
        "caja": None,
        "category": "anillo",
        "clasp": None,
        "coating": "oro rosa 18k",
        "description": "Anillo anillo solitario en acero con acabado oro rosa 18k.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "hombre",
        "id": 44,
        "metal": "acero",
        "name": "Anillo Solitario Tous 25",
        "price": 217.6,
        "ring_type": "Anillo Solitario",
        "url_image": "https://source.unsplash.com/featured/?ring,Tous,Sin%20gema",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 20,
    },
    {
        "bracelet": None,
        "brand": "Agatha",
        "caja": None,
        "category": "pendientes",
        "clasp": None,
        "coating": "rodio",
        "description": "Pendientes de aro en plata de primera ley.",
        "earring_type": "Pendiente Aro",
        "gem": "Sin gema",
        "gender": "mujer",
        "id": 11,
        "metal": "plata de primera ley",
        "name": "Pendientes aro plata",
        "price": 39.9,
        "ring_type": None,
        "url_image": "https://i.pinimg.com/1200x/7d/4f/b2/7d4fb229bb764d23221c052de12d1f41.jpg",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 30,
    },
    {
        "bracelet": None,
        "brand": "Guess",
        "caja": None,
        "category": "pendientes",
        "clasp": None,
        "coating": "oro rosa 18 k",
        "description": "Pendiente ear cuff en oro rosa de 18k.",
        "earring_type": "Pendiente Ear Cuff",
        "gem": "Sin gema",
        "gender": "mujer",
        "id": 12,
        "metal": "oro rosa 18 k",
        "name": "Ear cuff oro rosa",
        "price": 59.9,
        "ring_type": None,
        "url_image": "https://i.pinimg.com/1200x/f5/e0/18/f5e0184540ddc9164cfa4e807a436d76.jpg",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 12,
    },
    {
        "bracelet": None,
        "brand": "Calvin Klein",
        "caja": None,
        "category": "pendientes",
        "clasp": None,
        "coating": "rodio",
        "description": "Pendientes largos con perla cultivada.",
        "earring_type": "Pendiente Largo",
        "gem": "Perla cultivada",
        "gender": "mujer",
        "id": 13,
        "metal": "plata de primera ley",
        "name": "Pendientes largos perla cultivada",
        "price": 79.0,
        "ring_type": None,
        "url_image": "https://i.pinimg.com/1200x/b1/c4/66/b1c46656f78a08a9d9153e148a9b606a.jpg",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 15,
    },
    {
        "bracelet": None,
        "brand": "Pandora",
        "caja": None,
        "category": "pendientes",
        "clasp": None,
        "coating": None,
        "description": "Pendientes tipo pendiente aro en oro amarillo 18k con esmeralda.",
        "earring_type": "Pendiente Aro",
        "gem": "Esmeralda",
        "gender": "mujer",
        "id": 45,
        "metal": "oro amarillo 18k",
        "name": "Pendientes Aro Pandora 4",
        "price": 46.7,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?earrings,Pandora,Esmeralda",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 17,
    },
    {
        "bracelet": None,
        "brand": "Swarovski",
        "caja": None,
        "category": "pendientes",
        "clasp": None,
        "coating": "oro amarillo 18k",
        "description": "Pendientes tipo pendiente aro en plata de primera ley con rubí.",
        "earring_type": "Pendiente Aro",
        "gem": "Rubí",
        "gender": "hombre",
        "id": 46,
        "metal": "plata de primera ley",
        "name": "Pendientes Aro Swarovski 5",
        "price": 52.3,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?earrings,Swarovski,Rubí",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 20,
    },
    {
        "bracelet": None,
        "brand": "UNOde50",
        "caja": None,
        "category": "pendientes",
        "clasp": None,
        "coating": "oro amarillo 18k",
        "description": "Pendientes tipo pendiente ear cuff en oro amarillo 18k con esmeralda.",
        "earring_type": "Pendiente Ear Cuff",
        "gem": "Esmeralda",
        "gender": "mujer",
        "id": 47,
        "metal": "oro amarillo 18k",
        "name": "Pendientes Cuff UNOde50 6",
        "price": 58.1,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?earrings,UNOde50,Esmeralda",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 23,
    },
    {
        "bracelet": None,
        "brand": "Pandora",
        "caja": None,
        "category": "pendientes",
        "clasp": None,
        "coating": "oro rosa 18k",
        "description": "Pendientes tipo pendiente aro en acero con zafiro.",
        "earring_type": "Pendiente Aro",
        "gem": "Zafiro",
        "gender": "mujer",
        "id": 48,
        "metal": "acero",
        "name": "Pendientes Aro Pandora 7",
        "price": 63.7,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?earrings,Pandora,Zafiro",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 26,
    },
    {
        "bracelet": None,
        "brand": "Viceroy",
        "caja": None,
        "category": "pendientes",
        "clasp": None,
        "coating": "oro rosa 18k",
        "description": "Pendientes tipo pendiente aro en oro blanco 18k con amatista.",
        "earring_type": "Pendiente Aro",
        "gem": "Amatista",
        "gender": "mujer",
        "id": 49,
        "metal": "oro blanco 18k",
        "name": "Pendientes Aro Viceroy 8",
        "price": 69.2,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?earrings,Viceroy,Amatista",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 29,
    },
    {
        "bracelet": None,
        "brand": "Viceroy",
        "caja": None,
        "category": "pendientes",
        "clasp": None,
        "coating": None,
        "description": "Pendientes tipo pendiente aro en oro amarillo 18k con amatista.",
        "earring_type": "Pendiente Aro",
        "gem": "Amatista",
        "gender": "mujer",
        "id": 50,
        "metal": "oro amarillo 18k",
        "name": "Pendientes Aro Viceroy 9",
        "price": 74.9,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?earrings,Viceroy,Amatista",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 32,
    },
    {
        "bracelet": None,
        "brand": "Guess",
        "caja": None,
        "category": "pendientes",
        "clasp": None,
        "coating": "rodio",
        "description": "Pendientes tipo pendiente botón en oro blanco 18k con esmeralda.",
        "earring_type": "Pendiente Botón",
        "gem": "Esmeralda",
        "gender": "mujer",
        "id": 51,
        "metal": "oro blanco 18k",
        "name": "Pendientes Botón Guess 10",
        "price": 80.4,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?earrings,Guess,Esmeralda",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 35,
    },
    {
        "bracelet": None,
        "brand": "PDPAOLA",
        "caja": None,
        "category": "pendientes",
        "clasp": None,
        "coating": "oro rosa 18k",
        "description": "Pendientes tipo pendiente largo en oro amarillo 18k con perla cultivada.",
        "earring_type": "Pendiente Largo",
        "gem": "Perla cultivada",
        "gender": "mujer",
        "id": 52,
        "metal": "oro amarillo 18k",
        "name": "Pendientes Largo PDPAOLA 11",
        "price": 86.0,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?earrings,PDPAOLA,Perla%20cultivada",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 38,
    },
    {
        "bracelet": None,
        "brand": "Viceroy",
        "caja": None,
        "category": "pendientes",
        "clasp": None,
        "coating": None,
        "description": "Pendientes tipo pendiente ear cuff en plata de primera ley con amatista.",
        "earring_type": "Pendiente Ear Cuff",
        "gem": "Amatista",
        "gender": "mujer",
        "id": 53,
        "metal": "plata de primera ley",
        "name": "Pendientes Cuff Viceroy 12",
        "price": 91.7,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?earrings,Viceroy,Amatista",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 41,
    },
    {
        "bracelet": None,
        "brand": "Viceroy",
        "caja": None,
        "category": "pendientes",
        "clasp": None,
        "coating": "oro amarillo 18k",
        "description": "Pendientes tipo pendiente largo en acero con esmeralda.",
        "earring_type": "Pendiente Largo",
        "gem": "Esmeralda",
        "gender": "mujer",
        "id": 54,
        "metal": "acero",
        "name": "Pendientes Largo Viceroy 13",
        "price": 97.1,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?earrings,Viceroy,Esmeralda",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 44,
    },
    {
        "bracelet": None,
        "brand": "Pandora",
        "caja": None,
        "category": "pendientes",
        "clasp": None,
        "coating": "oro amarillo 18k",
        "description": "Pendientes tipo pendiente aro en oro amarillo 18k con circonita.",
        "earring_type": "Pendiente Aro",
        "gem": "Circonita",
        "gender": "mujer",
        "id": 55,
        "metal": "oro amarillo 18k",
        "name": "Pendientes Aro Pandora 14",
        "price": 103.2,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?earrings,Pandora,Circonita",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 47,
    },
    {
        "bracelet": None,
        "brand": "Viceroy",
        "caja": None,
        "category": "pendientes",
        "clasp": None,
        "coating": None,
        "description": "Pendientes tipo pendiente ear cuff en plata de primera ley con zafiro.",
        "earring_type": "Pendiente Ear Cuff",
        "gem": "Zafiro",
        "gender": "hombre",
        "id": 56,
        "metal": "plata de primera ley",
        "name": "Pendientes Cuff Viceroy 15",
        "price": 108.4,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?earrings,Viceroy,Zafiro",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 50,
    },
    {
        "bracelet": None,
        "brand": "UNOde50",
        "caja": None,
        "category": "pendientes",
        "clasp": None,
        "coating": None,
        "description": "Pendientes tipo pendiente ear cuff en oro blanco 18k con amatista.",
        "earring_type": "Pendiente Ear Cuff",
        "gem": "Amatista",
        "gender": "mujer",
        "id": 57,
        "metal": "oro blanco 18k",
        "name": "Pendientes Cuff UNOde50 16",
        "price": 114.4,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?earrings,UNOde50,Amatista",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 53,
    },
    {
        "bracelet": None,
        "brand": "Tous",
        "caja": None,
        "category": "pendientes",
        "clasp": None,
        "coating": "rodio",
        "description": "Pendientes tipo pendiente largo en oro amarillo 18k con circonita.",
        "earring_type": "Pendiente Largo",
        "gem": "Circonita",
        "gender": "mujer",
        "id": 58,
        "metal": "oro amarillo 18k",
        "name": "Pendientes Largo Tous 17",
        "price": 119.5,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?earrings,Tous,Circonita",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 56,
    },
    {
        "bracelet": None,
        "brand": "Pandora",
        "caja": None,
        "category": "pendientes",
        "clasp": None,
        "coating": "oro rosa 18k",
        "description": "Pendientes tipo pendiente largo en oro amarillo 18k con perla cultivada.",
        "earring_type": "Pendiente Largo",
        "gem": "Perla cultivada",
        "gender": "mujer",
        "id": 59,
        "metal": "oro amarillo 18k",
        "name": "Pendientes Largo Pandora 18",
        "price": 125.3,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?earrings,Pandora,Perla%20cultivada",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 59,
    },
    {
        "bracelet": None,
        "brand": "Swarovski",
        "caja": None,
        "category": "pendientes",
        "clasp": None,
        "coating": None,
        "description": "Pendientes tipo pendiente largo en plata de primera ley con amatista.",
        "earring_type": "Pendiente Largo",
        "gem": "Amatista",
        "gender": "mujer",
        "id": 60,
        "metal": "plata de primera ley",
        "name": "Pendientes Largo Swarovski 19",
        "price": 130.7,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?earrings,Swarovski,Amatista",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 62,
    },
    {
        "bracelet": None,
        "brand": "PDPAOLA",
        "caja": None,
        "category": "pendientes",
        "clasp": None,
        "coating": None,
        "description": "Pendientes tipo pendiente botón en oro amarillo 18k con esmeralda.",
        "earring_type": "Pendiente Botón",
        "gem": "Esmeralda",
        "gender": "mujer",
        "id": 61,
        "metal": "oro amarillo 18k",
        "name": "Pendientes Botón PDPAOLA 20",
        "price": 136.4,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?earrings,PDPAOLA,Esmeralda",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 65,
    },
    {
        "bracelet": None,
        "brand": "Viceroy",
        "caja": None,
        "category": "pendientes",
        "clasp": None,
        "coating": "oro rosa 18k",
        "description": "Pendientes tipo pendiente aro en oro blanco 18k con amatista.",
        "earring_type": "Pendiente Aro",
        "gem": "Amatista",
        "gender": "hombre",
        "id": 62,
        "metal": "oro blanco 18k",
        "name": "Pendientes Aro Viceroy 21",
        "price": 142.0,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?earrings,Viceroy,Amatista",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 8,
    },
    {
        "bracelet": None,
        "brand": "Viceroy",
        "caja": None,
        "category": "pendientes",
        "clasp": None,
        "coating": "oro rosa 18k",
        "description": "Pendientes tipo pendiente largo en acero con amatista.",
        "earring_type": "Pendiente Largo",
        "gem": "Amatista",
        "gender": "mujer",
        "id": 63,
        "metal": "acero",
        "name": "Pendientes Largo Viceroy 22",
        "price": 147.6,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?earrings,Viceroy,Amatista",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 11,
    },
    {
        "bracelet": None,
        "brand": "Agatha",
        "caja": None,
        "category": "pendientes",
        "clasp": None,
        "coating": "rodio",
        "description": "Pendientes tipo pendiente largo en acero con rubí.",
        "earring_type": "Pendiente Largo",
        "gem": "Rubí",
        "gender": "mujer",
        "id": 64,
        "metal": "acero",
        "name": "Pendientes Largo Agatha 23",
        "price": 153.1,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?earrings,Agatha,Rubí",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 14,
    },
    {
        "bracelet": None,
        "brand": "Pandora",
        "caja": None,
        "category": "pendientes",
        "clasp": None,
        "coating": None,
        "description": "Pendientes tipo pendiente aro en plata de primera ley con esmeralda.",
        "earring_type": "Pendiente Aro",
        "gem": "Esmeralda",
        "gender": "hombre",
        "id": 65,
        "metal": "plata de primera ley",
        "name": "Pendientes Aro Pandora 24",
        "price": 159.2,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?earrings,Pandora,Esmeralda",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 17,
    },
    {
        "bracelet": None,
        "brand": "Agatha",
        "caja": None,
        "category": "pendientes",
        "clasp": None,
        "coating": "rodio",
        "description": "Pendientes tipo pendiente aro en oro amarillo 18k con esmeralda.",
        "earring_type": "Pendiente Aro",
        "gem": "Esmeralda",
        "gender": "mujer",
        "id": 66,
        "metal": "oro amarillo 18k",
        "name": "Pendientes Aro Agatha 25",
        "price": 164.3,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?earrings,Agatha,Esmeralda",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 20,
    },
    {
        "bracelet": "Pulsera Bolas",
        "brand": "Viceroy",
        "caja": None,
        "category": "pulseras",
        "clasp": "Ajustable",
        "coating": "rodio",
        "description": "Pulsera de bolas en plata, ajuste fácil.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "mujer",
        "id": 14,
        "metal": "plata de primera ley",
        "name": "Pulsera bolas plata",
        "price": 49.9,
        "ring_type": None,
        "url_image": "https://i.pinimg.com/736x/cf/e2/80/cfe280340476a7e230fafe0aa55d6652.jpg",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 25,
    },
    {
        "bracelet": "Pulsera Malla",
        "brand": "Tommy Hilfiger",
        "caja": None,
        "category": "pulseras",
        "clasp": "De pulsera",
        "coating": None,
        "description": "Pulsera de malla en acero para look urbano.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "hombre",
        "id": 15,
        "metal": "acero",
        "name": "Pulsera malla acero",
        "price": 79.0,
        "ring_type": None,
        "url_image": "https://i.pinimg.com/1200x/1a/9f/fb/1a9ffbff2319594b0d0b168931fc8649.jpg",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 40,
    },
    {
        "bracelet": "Pulsera Riviere",
        "brand": "Tous",
        "caja": None,
        "category": "pulseras",
        "clasp": "De pulsera",
        "coating": "rodio",
        "description": "Pulsera riviere con circonitas montadas en plata.",
        "earring_type": None,
        "gem": "Circonita",
        "gender": "mujer",
        "id": 17,
        "metal": "plata de primera ley",
        "name": "Pulsera riviere circonitas",
        "price": 129.0,
        "ring_type": None,
        "url_image": "https://i.pinimg.com/1200x/d6/02/51/d60251048e7c8bb0c2e4ff57c8bd3ee2.jpg",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 18,
    },
    {
        "bracelet": "Pulsera Eslabones",
        "brand": "Fossil",
        "caja": None,
        "category": "pulseras",
        "clasp": "Ajustable",
        "coating": None,
        "description": "Pulsera Eslabones en plata de primera ley con acabado pulido.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "hombre",
        "id": 67,
        "metal": "plata de primera ley",
        "name": "Pulsera Eslabones Fossil 4",
        "price": 65.5,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?bracelet,Fossil",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 17,
    },
    {
        "bracelet": "Pulsera Eslabones",
        "brand": "Fossil",
        "caja": None,
        "category": "pulseras",
        "clasp": "De pulsera",
        "coating": "oro amarillo 18k",
        "description": "Pulsera Eslabones en oro amarillo 18k con acabado oro amarillo 18k.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "hombre",
        "id": 68,
        "metal": "oro amarillo 18k",
        "name": "Pulsera Eslabones Fossil 5",
        "price": 72.6,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?bracelet,Fossil",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 20,
    },
    {
        "bracelet": "Pulsera Malla",
        "brand": "Tous",
        "caja": None,
        "category": "pulseras",
        "clasp": "Ajustable",
        "coating": "rodio",
        "description": "Pulsera Malla en oro blanco 18k con acabado rodio.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "mujer",
        "id": 69,
        "metal": "oro blanco 18k",
        "name": "Pulsera Malla Tous 6",
        "price": 79.4,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?bracelet,Tous",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 23,
    },
    {
        "bracelet": "Pulsera Bolas",
        "brand": "Michael Kors",
        "caja": None,
        "category": "pulseras",
        "clasp": "De pulsera",
        "coating": "oro amarillo 18k",
        "description": "Pulsera Bolas en acero con acabado oro amarillo 18k.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "mujer",
        "id": 70,
        "metal": "acero",
        "name": "Pulsera Bolas Michael Kors 7",
        "price": 85.8,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?bracelet,Michael%20Kors",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 26,
    },
    {
        "bracelet": "Pulsera Riviere",
        "brand": "Tous",
        "caja": None,
        "category": "pulseras",
        "clasp": "Ajustable",
        "coating": None,
        "description": "Pulsera Riviere en oro blanco 18k con acabado pulido.",
        "earring_type": None,
        "gem": "Esmeralda",
        "gender": "mujer",
        "id": 71,
        "metal": "oro blanco 18k",
        "name": "Pulsera Riviere Tous 8",
        "price": 92.6,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?bracelet,Tous",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 29,
    },
    {
        "bracelet": "Pulsera Bolas",
        "brand": "Tommy Hilfiger",
        "caja": None,
        "category": "pulseras",
        "clasp": "De pulsera",
        "coating": "rodio",
        "description": "Pulsera Bolas en acero con acabado rodio.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "hombre",
        "id": 72,
        "metal": "acero",
        "name": "Pulsera Bolas Tommy Hilfiger 9",
        "price": 99.3,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?bracelet,Tommy%20Hilfiger",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 32,
    },
    {
        "bracelet": "Pulsera Eslabones",
        "brand": "Tommy Hilfiger",
        "caja": None,
        "category": "pulseras",
        "clasp": "Ajustable",
        "coating": "rodio",
        "description": "Pulsera Eslabones en oro amarillo 18k con acabado rodio.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "mujer",
        "id": 73,
        "metal": "oro amarillo 18k",
        "name": "Pulsera Eslabones Tommy Hilfiger 10",
        "price": 106.6,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?bracelet,Tommy%20Hilfiger",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 35,
    },
    {
        "bracelet": "Pulsera Riviere",
        "brand": "Michael Kors",
        "caja": None,
        "category": "pulseras",
        "clasp": "De pulsera",
        "coating": "oro amarillo 18k",
        "description": "Pulsera Riviere en oro amarillo 18k con acabado oro amarillo 18k.",
        "earring_type": None,
        "gem": "Circonita",
        "gender": "mujer",
        "id": 74,
        "metal": "oro amarillo 18k",
        "name": "Pulsera Riviere Michael Kors 11",
        "price": 112.9,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?bracelet,Michael%20Kors",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 38,
    },
    {
        "bracelet": "Pulsera Eslabones",
        "brand": "Michael Kors",
        "caja": None,
        "category": "pulseras",
        "clasp": "Ajustable",
        "coating": None,
        "description": "Pulsera Eslabones en acero con acabado pulido.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "mujer",
        "id": 75,
        "metal": "acero",
        "name": "Pulsera Eslabones Michael Kors 12",
        "price": 119.9,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?bracelet,Michael%20Kors",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 41,
    },
    {
        "bracelet": "Pulsera Cadena",
        "brand": "Fossil",
        "caja": None,
        "category": "pulseras",
        "clasp": "De pulsera",
        "coating": None,
        "description": "Pulsera Cadena en plata de primera ley con acabado pulido.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "mujer",
        "id": 76,
        "metal": "plata de primera ley",
        "name": "Pulsera Cadena Fossil 13",
        "price": 126.6,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?bracelet,Fossil",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 44,
    },
    {
        "bracelet": "Pulsera Bolas",
        "brand": "Guess",
        "caja": None,
        "category": "pulseras",
        "clasp": "Ajustable",
        "coating": "rodio",
        "description": "Pulsera Bolas en plata de primera ley con acabado rodio.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "hombre",
        "id": 77,
        "metal": "plata de primera ley",
        "name": "Pulsera Bolas Guess 14",
        "price": 133.4,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?bracelet,Guess",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 47,
    },
    {
        "bracelet": "Pulsera Riviere",
        "brand": "Tous",
        "caja": None,
        "category": "pulseras",
        "clasp": "De pulsera",
        "coating": "oro rosa 18k",
        "description": "Pulsera Riviere en oro blanco 18k con acabado oro rosa 18k.",
        "earring_type": None,
        "gem": "Circonita",
        "gender": "mujer",
        "id": 78,
        "metal": "oro blanco 18k",
        "name": "Pulsera Riviere Tous 15",
        "price": 140.6,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?bracelet,Tous",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 50,
    },
    {
        "bracelet": "Pulsera Cadena",
        "brand": "Tous",
        "caja": None,
        "category": "pulseras",
        "clasp": "Ajustable",
        "coating": "oro rosa 18k",
        "description": "Pulsera Cadena en oro amarillo 18k con acabado oro rosa 18k.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "mujer",
        "id": 79,
        "metal": "oro amarillo 18k",
        "name": "Pulsera Cadena Tous 16",
        "price": 147.1,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?bracelet,Tous",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 53,
    },
    {
        "bracelet": "Pulsera Cadena",
        "brand": "Guess",
        "caja": None,
        "category": "pulseras",
        "clasp": "De pulsera",
        "coating": "rodio",
        "description": "Pulsera Cadena en plata de primera ley con acabado rodio.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "mujer",
        "id": 80,
        "metal": "plata de primera ley",
        "name": "Pulsera Cadena Guess 17",
        "price": 153.9,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?bracelet,Guess",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 56,
    },
    {
        "bracelet": "Pulsera Cadena",
        "brand": "Guess",
        "caja": None,
        "category": "pulseras",
        "clasp": "Ajustable",
        "coating": "oro amarillo 18k",
        "description": "Pulsera Cadena en acero con acabado oro amarillo 18k.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "mujer",
        "id": 81,
        "metal": "acero",
        "name": "Pulsera Cadena Guess 18",
        "price": 160.6,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?bracelet,Guess",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 59,
    },
    {
        "bracelet": "Pulsera Malla",
        "brand": "Tommy Hilfiger",
        "caja": None,
        "category": "pulseras",
        "clasp": "De pulsera",
        "coating": "rodio",
        "description": "Pulsera Malla en plata de primera ley con acabado rodio.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "mujer",
        "id": 82,
        "metal": "plata de primera ley",
        "name": "Pulsera Malla Tommy Hilfiger 19",
        "price": 167.3,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?bracelet,Tommy%20Hilfiger",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 62,
    },
    {
        "bracelet": "Pulsera Eslabones",
        "brand": "Guess",
        "caja": None,
        "category": "pulseras",
        "clasp": "Ajustable",
        "coating": "rodio",
        "description": "Pulsera Eslabones en oro blanco 18k con acabado rodio.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "mujer",
        "id": 83,
        "metal": "oro blanco 18k",
        "name": "Pulsera Eslabones Guess 20",
        "price": 174.6,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?bracelet,Guess",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 65,
    },
    {
        "bracelet": "Pulsera Cadena",
        "brand": "Guess",
        "caja": None,
        "category": "pulseras",
        "clasp": "De pulsera",
        "coating": None,
        "description": "Pulsera Cadena en oro blanco 18k con acabado pulido.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "mujer",
        "id": 84,
        "metal": "oro blanco 18k",
        "name": "Pulsera Cadena Guess 21",
        "price": 180.9,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?bracelet,Guess",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 8,
    },
    {
        "bracelet": "Pulsera Cadena",
        "brand": "Fossil",
        "caja": None,
        "category": "pulseras",
        "clasp": "Ajustable",
        "coating": "oro rosa 18k",
        "description": "Pulsera Cadena en oro amarillo 18k con acabado oro rosa 18k.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "mujer",
        "id": 85,
        "metal": "oro amarillo 18k",
        "name": "Pulsera Cadena Fossil 22",
        "price": 188.2,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?bracelet,Fossil",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 11,
    },
    {
        "bracelet": "Pulsera Eslabones",
        "brand": "Tous",
        "caja": None,
        "category": "pulseras",
        "clasp": "De pulsera",
        "coating": "oro rosa 18k",
        "description": "Pulsera Eslabones en acero con acabado oro rosa 18k.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "mujer",
        "id": 86,
        "metal": "acero",
        "name": "Pulsera Eslabones Tous 23",
        "price": 195.0,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?bracelet,Tous",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 14,
    },
    {
        "bracelet": "Pulsera Bolas",
        "brand": "Tommy Hilfiger",
        "caja": None,
        "category": "pulseras",
        "clasp": "Ajustable",
        "coating": "oro amarillo 18k",
        "description": "Pulsera Bolas en oro amarillo 18k con acabado oro amarillo 18k.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "hombre",
        "id": 87,
        "metal": "oro amarillo 18k",
        "name": "Pulsera Bolas Tommy Hilfiger 24",
        "price": 201.4,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?bracelet,Tommy%20Hilfiger",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 17,
    },
    {
        "bracelet": "Pulsera Bolas",
        "brand": "Viceroy",
        "caja": None,
        "category": "pulseras",
        "clasp": "De pulsera",
        "coating": None,
        "description": "Pulsera Bolas en oro amarillo 18k con acabado pulido.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "mujer",
        "id": 88,
        "metal": "oro amarillo 18k",
        "name": "Pulsera Bolas Viceroy 25",
        "price": 208.3,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?bracelet,Viceroy",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 20,
    },
    {
        "bracelet": None,
        "brand": "Pandora",
        "caja": None,
        "category": "colgantes",
        "clasp": "Mosqueton",
        "coating": "rodio",
        "description": "Colgante con amatista en plata de primera ley.",
        "earring_type": None,
        "gem": "Amatista",
        "gender": "mujer",
        "id": 18,
        "metal": "plata de primera ley",
        "name": "Colgante amatista plata",
        "price": 89.0,
        "ring_type": None,
        "url_image": "https://i.pinimg.com/736x/4d/51/f3/4d51f3091da6baed50473b9f762664ad.jpg",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 22,
    },
    {
        "bracelet": None,
        "brand": "Pandora",
        "caja": None,
        "category": "colgantes",
        "clasp": "Mosqueton",
        "coating": "rodio",
        "description": "Colgante con amatista en plata de primera ley.",
        "earring_type": None,
        "gem": "Amatista",
        "gender": "mujer",
        "id": 19,
        "metal": "plata de primera ley",
        "name": "Colgante amatista plata",
        "price": 89.0,
        "ring_type": None,
        "url_image": "https://i.pinimg.com/1200x/13/46/a1/1346a10d6b947444731df9c466061091.jpg",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 20,
    },
    {
        "bracelet": None,
        "brand": "Pandora",
        "caja": None,
        "category": "colgantes",
        "clasp": "Mosqueton",
        "coating": "oro amarillo 18k",
        "description": "Colgante en acero con rubí y cierre mosquetón.",
        "earring_type": None,
        "gem": "Rubí",
        "gender": "mujer",
        "id": 89,
        "metal": "acero",
        "name": "Colgante Rubí Pandora 3",
        "price": 71.6,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?pendant,Pandora,Rubí",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 14,
    },
    {
        "bracelet": None,
        "brand": "Pandora",
        "caja": None,
        "category": "colgantes",
        "clasp": "Mosqueton",
        "coating": "rodio",
        "description": "Colgante en acero con circonita y cierre mosquetón.",
        "earring_type": None,
        "gem": "Circonita",
        "gender": "mujer",
        "id": 90,
        "metal": "acero",
        "name": "Colgante Circonita Pandora 4",
        "price": 80.0,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?pendant,Pandora,Circonita",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 17,
    },
    {
        "bracelet": None,
        "brand": "Tous",
        "caja": None,
        "category": "colgantes",
        "clasp": "Mosqueton",
        "coating": "oro amarillo 18k",
        "description": "Colgante en oro blanco 18k con rubí y cierre mosquetón.",
        "earring_type": None,
        "gem": "Rubí",
        "gender": "mujer",
        "id": 91,
        "metal": "oro blanco 18k",
        "name": "Colgante Rubí Tous 5",
        "price": 88.3,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?pendant,Tous,Rubí",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 20,
    },
    {
        "bracelet": None,
        "brand": "Tous",
        "caja": None,
        "category": "colgantes",
        "clasp": "Mosqueton",
        "coating": "oro amarillo 18k",
        "description": "Colgante en oro amarillo 18k con circonita y cierre mosquetón.",
        "earring_type": None,
        "gem": "Circonita",
        "gender": "mujer",
        "id": 92,
        "metal": "oro amarillo 18k",
        "name": "Colgante Circonita Tous 6",
        "price": 96.4,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?pendant,Tous,Circonita",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 23,
    },
    {
        "bracelet": None,
        "brand": "Pandora",
        "caja": None,
        "category": "colgantes",
        "clasp": "Mosqueton",
        "coating": "oro amarillo 18k",
        "description": "Colgante en acero con rubí y cierre mosquetón.",
        "earring_type": None,
        "gem": "Rubí",
        "gender": "mujer",
        "id": 93,
        "metal": "acero",
        "name": "Colgante Rubí Pandora 7",
        "price": 104.8,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?pendant,Pandora,Rubí",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 26,
    },
    {
        "bracelet": None,
        "brand": "Pandora",
        "caja": None,
        "category": "colgantes",
        "clasp": "Mosqueton",
        "coating": "oro amarillo 18k",
        "description": "Colgante en plata de primera ley con amatista y cierre mosquetón.",
        "earring_type": None,
        "gem": "Amatista",
        "gender": "mujer",
        "id": 94,
        "metal": "plata de primera ley",
        "name": "Colgante Amatista Pandora 8",
        "price": 113.0,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?pendant,Pandora,Amatista",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 29,
    },
    {
        "bracelet": None,
        "brand": "PDPAOLA",
        "caja": None,
        "category": "colgantes",
        "clasp": "Mosqueton",
        "coating": "oro rosa 18k",
        "description": "Colgante en plata de primera ley con sin gema y cierre mosquetón.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "mujer",
        "id": 95,
        "metal": "plata de primera ley",
        "name": "Colgante Sin gema PDPAOLA 9",
        "price": 121.5,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?pendant,PDPAOLA,Sin%20gema",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 32,
    },
    {
        "bracelet": None,
        "brand": "Swarovski",
        "caja": None,
        "category": "colgantes",
        "clasp": "Mosqueton",
        "coating": "rodio",
        "description": "Colgante en plata de primera ley con perla cultivada y cierre mosquetón.",
        "earring_type": None,
        "gem": "Perla cultivada",
        "gender": "hombre",
        "id": 96,
        "metal": "plata de primera ley",
        "name": "Colgante Perla cultivada Swarovski 10",
        "price": 130.1,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?pendant,Swarovski,Perla%20cultivada",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 35,
    },
    {
        "bracelet": None,
        "brand": "Luxenter",
        "caja": None,
        "category": "colgantes",
        "clasp": "Mosqueton",
        "coating": "rodio",
        "description": "Colgante en acero con esmeralda y cierre mosquetón.",
        "earring_type": None,
        "gem": "Esmeralda",
        "gender": "mujer",
        "id": 97,
        "metal": "acero",
        "name": "Colgante Esmeralda Luxenter 11",
        "price": 138.0,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?pendant,Luxenter,Esmeralda",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": True,
        "quantity": 38,
    },
    {
        "bracelet": None,
        "brand": "Luxenter",
        "caja": None,
        "category": "colgantes",
        "clasp": "Mosqueton",
        "coating": "rodio",
        "description": "Colgante en acero con rubí y cierre mosquetón.",
        "earring_type": None,
        "gem": "Rubí",
        "gender": "hombre",
        "id": 98,
        "metal": "acero",
        "name": "Colgante Rubí Luxenter 12",
        "price": 146.2,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?pendant,Luxenter,Rubí",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 41,
    },
    {
        "bracelet": None,
        "brand": "PDPAOLA",
        "caja": None,
        "category": "colgantes",
        "clasp": "Mosqueton",
        "coating": None,
        "description": "Colgante en oro amarillo 18k con sin gema y cierre mosquetón.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "mujer",
        "id": 99,
        "metal": "oro amarillo 18k",
        "name": "Colgante Sin gema PDPAOLA 13",
        "price": 154.5,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?pendant,PDPAOLA,Sin%20gema",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 44,
    },
    {
        "bracelet": None,
        "brand": "Tous",
        "caja": None,
        "category": "colgantes",
        "clasp": "Mosqueton",
        "coating": "oro rosa 18k",
        "description": "Colgante en plata de primera ley con amatista y cierre mosquetón.",
        "earring_type": None,
        "gem": "Amatista",
        "gender": "mujer",
        "id": 100,
        "metal": "plata de primera ley",
        "name": "Colgante Amatista Tous 14",
        "price": 163.3,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?pendant,Tous,Amatista",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 47,
    },
    {
        "bracelet": None,
        "brand": "Luxenter",
        "caja": None,
        "category": "colgantes",
        "clasp": "Mosqueton",
        "coating": "rodio",
        "description": "Colgante en plata de primera ley con zafiro y cierre mosquetón.",
        "earring_type": None,
        "gem": "Zafiro",
        "gender": "mujer",
        "id": 101,
        "metal": "plata de primera ley",
        "name": "Colgante Zafiro Luxenter 15",
        "price": 171.3,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?pendant,Luxenter,Zafiro",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 50,
    },
    {
        "bracelet": None,
        "brand": "Pandora",
        "caja": None,
        "category": "colgantes",
        "clasp": "Mosqueton",
        "coating": None,
        "description": "Colgante en plata de primera ley con perla cultivada y cierre mosquetón.",
        "earring_type": None,
        "gem": "Perla cultivada",
        "gender": "mujer",
        "id": 102,
        "metal": "plata de primera ley",
        "name": "Colgante Perla cultivada Pandora 16",
        "price": 179.9,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?pendant,Pandora,Perla%20cultivada",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 53,
    },
    {
        "bracelet": None,
        "brand": "Pandora",
        "caja": None,
        "category": "colgantes",
        "clasp": "Mosqueton",
        "coating": "rodio",
        "description": "Colgante en oro blanco 18k con perla cultivada y cierre mosquetón.",
        "earring_type": None,
        "gem": "Perla cultivada",
        "gender": "mujer",
        "id": 103,
        "metal": "oro blanco 18k",
        "name": "Colgante Perla cultivada Pandora 17",
        "price": 187.8,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?pendant,Pandora,Perla%20cultivada",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 56,
    },
    {
        "bracelet": None,
        "brand": "Luxenter",
        "caja": None,
        "category": "colgantes",
        "clasp": "Mosqueton",
        "coating": "oro rosa 18k",
        "description": "Colgante en acero con amatista y cierre mosquetón.",
        "earring_type": None,
        "gem": "Amatista",
        "gender": "mujer",
        "id": 104,
        "metal": "acero",
        "name": "Colgante Amatista Luxenter 18",
        "price": 196.5,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?pendant,Luxenter,Amatista",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 59,
    },
    {
        "bracelet": None,
        "brand": "Luxenter",
        "caja": None,
        "category": "colgantes",
        "clasp": "Mosqueton",
        "coating": None,
        "description": "Colgante en oro blanco 18k con rubí y cierre mosquetón.",
        "earring_type": None,
        "gem": "Rubí",
        "gender": "mujer",
        "id": 105,
        "metal": "oro blanco 18k",
        "name": "Colgante Rubí Luxenter 19",
        "price": 204.4,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?pendant,Luxenter,Rubí",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 62,
    },
    {
        "bracelet": None,
        "brand": "Swarovski",
        "caja": None,
        "category": "colgantes",
        "clasp": "Mosqueton",
        "coating": "oro amarillo 18k",
        "description": "Colgante en oro blanco 18k con perla cultivada y cierre mosquetón.",
        "earring_type": None,
        "gem": "Perla cultivada",
        "gender": "mujer",
        "id": 106,
        "metal": "oro blanco 18k",
        "name": "Colgante Perla cultivada Swarovski 20",
        "price": 212.8,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?pendant,Swarovski,Perla%20cultivada",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 65,
    },
    {
        "bracelet": None,
        "brand": "Swarovski",
        "caja": None,
        "category": "colgantes",
        "clasp": "Mosqueton",
        "coating": "oro rosa 18k",
        "description": "Colgante en plata de primera ley con sin gema y cierre mosquetón.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "mujer",
        "id": 107,
        "metal": "plata de primera ley",
        "name": "Colgante Sin gema Swarovski 21",
        "price": 221.4,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?pendant,Swarovski,Sin%20gema",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 8,
    },
    {
        "bracelet": None,
        "brand": "Luxenter",
        "caja": None,
        "category": "colgantes",
        "clasp": "Mosqueton",
        "coating": "rodio",
        "description": "Colgante en plata de primera ley con perla cultivada y cierre mosquetón.",
        "earring_type": None,
        "gem": "Perla cultivada",
        "gender": "mujer",
        "id": 108,
        "metal": "plata de primera ley",
        "name": "Colgante Perla cultivada Luxenter 22",
        "price": 229.7,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?pendant,Luxenter,Perla%20cultivada",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 11,
    },
    {
        "bracelet": None,
        "brand": "PDPAOLA",
        "caja": None,
        "category": "colgantes",
        "clasp": "Mosqueton",
        "coating": "oro rosa 18k",
        "description": "Colgante en oro blanco 18k con zafiro y cierre mosquetón.",
        "earring_type": None,
        "gem": "Zafiro",
        "gender": "hombre",
        "id": 109,
        "metal": "oro blanco 18k",
        "name": "Colgante Zafiro PDPAOLA 23",
        "price": 238.0,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?pendant,PDPAOLA,Zafiro",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 14,
    },
    {
        "bracelet": None,
        "brand": "PDPAOLA",
        "caja": None,
        "category": "colgantes",
        "clasp": "Mosqueton",
        "coating": "oro amarillo 18k",
        "description": "Colgante en oro amarillo 18k con sin gema y cierre mosquetón.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "mujer",
        "id": 110,
        "metal": "oro amarillo 18k",
        "name": "Colgante Sin gema PDPAOLA 24",
        "price": 246.3,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?pendant,PDPAOLA,Sin%20gema",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 17,
    },
    {
        "bracelet": None,
        "brand": "Majorica",
        "caja": None,
        "category": "colgantes",
        "clasp": "Mosqueton",
        "coating": "oro rosa 18k",
        "description": "Colgante en plata de primera ley con esmeralda y cierre mosquetón.",
        "earring_type": None,
        "gem": "Esmeralda",
        "gender": "mujer",
        "id": 111,
        "metal": "plata de primera ley",
        "name": "Colgante Esmeralda Majorica 25",
        "price": 254.6,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?pendant,Majorica,Esmeralda",
        "watch": None,
        "watch_bracelet_material": None,
        "water_resistance": None,
        "destacado": False,
        "quantity": 20,
    },
    {
        "bracelet": None,
        "brand": "Seiko",
        "caja": "Acero",
        "category": "relojes",
        "clasp": None,
        "coating": None,
        "description": "Reloj analógico de acero con resistencia 5ATM.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "hombre",
        "id": 20,
        "metal": "acero",
        "name": "Reloj analógico acero 5ATM",
        "price": 199.0,
        "ring_type": None,
        "url_image": "https://i.pinimg.com/1200x/9a/e3/c8/9ae3c8f059fd00f227e835796244f551.jpg",
        "watch": "Analogico",
        "watch_bracelet_material": "Acero",
        "water_resistance": "5ATM",
        "destacado": False,
        "quantity": 8,
    },
    {
        "bracelet": None,
        "brand": "Casio",
        "caja": "Resina",
        "category": "relojes",
        "clasp": None,
        "coating": None,
        "description": "Reloj digital deportivo, caja de resina, 10ATM.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "unisex",
        "id": 21,
        "metal": "acero",
        "name": "Reloj digital resina 10ATM",
        "price": 49.0,
        "ring_type": None,
        "url_image": "https://i.pinimg.com/736x/6a/8b/e5/6a8be5ebae4b1d6eec3e67876d21350e.jpg",
        "watch": "Digital",
        "watch_bracelet_material": "Nylon",
        "water_resistance": "10ATM",
        "destacado": False,
        "quantity": 50,
    },
    {
        "bracelet": None,
        "brand": "Mark Maddox",
        "caja": "Metal",
        "category": "relojes",
        "clasp": None,
        "coating": None,
        "description": "SmartWatch con caja metálica y correa de nylon.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "unisex",
        "id": 22,
        "metal": "acero",
        "name": "SmartWatch metal nylon",
        "price": 129.0,
        "ring_type": None,
        "url_image": "https://i.pinimg.com/736x/56/da/c8/56dac81dad15667931e6fd69719435ce.jpg",
        "watch": "SmartWatch",
        "watch_bracelet_material": "Nylon",
        "water_resistance": "3ATM",
        "destacado": True,
        "quantity": 35,
    },
    {
        "bracelet": None,
        "brand": "Fossil",
        "caja": "Acero",
        "category": "relojes",
        "clasp": None,
        "coating": None,
        "description": "Reloj digital con correa de Nylon y resistencia 10ATM.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "unisex",
        "id": 112,
        "metal": "acero",
        "name": "Reloj Digital Fossil 4",
        "price": 116.4,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?watch,Fossil,Digital",
        "watch": "Digital",
        "watch_bracelet_material": "Nylon",
        "water_resistance": "10ATM",
        "destacado": True,
        "quantity": 17,
    },
    {
        "bracelet": None,
        "brand": "Garmin",
        "caja": "Acero",
        "category": "relojes",
        "clasp": None,
        "coating": None,
        "description": "Reloj analogico con correa de Cuero y resistencia 5ATM.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "unisex",
        "id": 113,
        "metal": "acero",
        "name": "Reloj Analogico Garmin 5",
        "price": 128.8,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?watch,Garmin,Analogico",
        "watch": "Analogico",
        "watch_bracelet_material": "Cuero",
        "water_resistance": "5ATM",
        "destacado": True,
        "quantity": 20,
    },
    {
        "bracelet": None,
        "brand": "Huawei",
        "caja": "Metal",
        "category": "relojes",
        "clasp": None,
        "coating": "rodio",
        "description": "Reloj smartwatch con correa de Cuero y resistencia 5ATM.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "unisex",
        "id": 114,
        "metal": "acero",
        "name": "Reloj SmartWatch Huawei 6",
        "price": 141.5,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?watch,Huawei,SmartWatch",
        "watch": "SmartWatch",
        "watch_bracelet_material": "Cuero",
        "water_resistance": "5ATM",
        "destacado": True,
        "quantity": 23,
    },
    {
        "bracelet": None,
        "brand": "Tissot",
        "caja": "Acero",
        "category": "relojes",
        "clasp": None,
        "coating": "oro rosa 18k",
        "description": "Reloj digital con correa de Acero y resistencia 5ATM.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "unisex",
        "id": 115,
        "metal": "acero",
        "name": "Reloj Digital Tissot 7",
        "price": 153.9,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?watch,Tissot,Digital",
        "watch": "Digital",
        "watch_bracelet_material": "Acero",
        "water_resistance": "5ATM",
        "destacado": True,
        "quantity": 26,
    },
    {
        "bracelet": None,
        "brand": "Seiko",
        "caja": "Acero",
        "category": "relojes",
        "clasp": None,
        "coating": "oro amarillo 18k",
        "description": "Reloj analogico con correa de Nylon y resistencia 10ATM.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "unisex",
        "id": 116,
        "metal": "acero",
        "name": "Reloj Analogico Seiko 8",
        "price": 166.3,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?watch,Seiko,Analogico",
        "watch": "Analogico",
        "watch_bracelet_material": "Nylon",
        "water_resistance": "10ATM",
        "destacado": True,
        "quantity": 29,
    },
    {
        "bracelet": None,
        "brand": "Seiko",
        "caja": "Acero",
        "category": "relojes",
        "clasp": None,
        "coating": "oro amarillo 18k",
        "description": "Reloj digital con correa de Cuero y resistencia 10ATM.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "unisex",
        "id": 117,
        "metal": "acero",
        "name": "Reloj Digital Seiko 9",
        "price": 178.2,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?watch,Seiko,Digital",
        "watch": "Digital",
        "watch_bracelet_material": "Cuero",
        "water_resistance": "10ATM",
        "destacado": True,
        "quantity": 32,
    },
    {
        "bracelet": None,
        "brand": "Casio",
        "caja": "Acero",
        "category": "relojes",
        "clasp": None,
        "coating": "oro rosa 18k",
        "description": "Reloj analogico con correa de Silicona y resistencia 3ATM.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "unisex",
        "id": 118,
        "metal": "acero",
        "name": "Reloj Analogico Casio 10",
        "price": 190.8,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?watch,Casio,Analogico",
        "watch": "Analogico",
        "watch_bracelet_material": "Silicona",
        "water_resistance": "3ATM",
        "destacado": True,
        "quantity": 35,
    },
    {
        "bracelet": None,
        "brand": "Seiko",
        "caja": "Acero",
        "category": "relojes",
        "clasp": None,
        "coating": "rodio",
        "description": "Reloj digital con correa de Silicona y resistencia 3ATM.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "unisex",
        "id": 119,
        "metal": "acero",
        "name": "Reloj Digital Seiko 11",
        "price": 203.2,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?watch,Seiko,Digital",
        "watch": "Digital",
        "watch_bracelet_material": "Silicona",
        "water_resistance": "3ATM",
        "destacado": True,
        "quantity": 38,
    },
    {
        "bracelet": None,
        "brand": "Swatch",
        "caja": "Metal",
        "category": "relojes",
        "clasp": None,
        "coating": None,
        "description": "Reloj smartwatch con correa de Nylon y resistencia 10ATM.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "unisex",
        "id": 120,
        "metal": "acero",
        "name": "Reloj SmartWatch Swatch 12",
        "price": 215.9,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?watch,Swatch,SmartWatch",
        "watch": "SmartWatch",
        "watch_bracelet_material": "Nylon",
        "water_resistance": "10ATM",
        "destacado": True,
        "quantity": 41,
    },
    {
        "bracelet": None,
        "brand": "Casio",
        "caja": "Metal",
        "category": "relojes",
        "clasp": None,
        "coating": "oro rosa 18k",
        "description": "Reloj smartwatch con correa de Silicona y resistencia 5ATM.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "unisex",
        "id": 121,
        "metal": "acero",
        "name": "Reloj SmartWatch Casio 13",
        "price": 227.9,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?watch,Casio,SmartWatch",
        "watch": "SmartWatch",
        "watch_bracelet_material": "Silicona",
        "water_resistance": "5ATM",
        "destacado": False,
        "quantity": 44,
    },
    {
        "bracelet": None,
        "brand": "Seiko",
        "caja": "Acero",
        "category": "relojes",
        "clasp": None,
        "coating": "rodio",
        "description": "Reloj digital con correa de Silicona y resistencia 5ATM.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "unisex",
        "id": 122,
        "metal": "acero",
        "name": "Reloj Digital Seiko 14",
        "price": 240.7,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?watch,Seiko,Digital",
        "watch": "Digital",
        "watch_bracelet_material": "Silicona",
        "water_resistance": "5ATM",
        "destacado": False,
        "quantity": 47,
    },
    {
        "bracelet": None,
        "brand": "Tissot",
        "caja": "Acero",
        "category": "relojes",
        "clasp": None,
        "coating": "oro rosa 18k",
        "description": "Reloj digital con correa de Cuero y resistencia 10ATM.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "unisex",
        "id": 123,
        "metal": "acero",
        "name": "Reloj Digital Tissot 15",
        "price": 252.7,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?watch,Tissot,Digital",
        "watch": "Digital",
        "watch_bracelet_material": "Cuero",
        "water_resistance": "10ATM",
        "destacado": False,
        "quantity": 50,
    },
    {
        "bracelet": None,
        "brand": "Huawei",
        "caja": "Acero",
        "category": "relojes",
        "clasp": None,
        "coating": "rodio",
        "description": "Reloj analogico con correa de Nylon y resistencia 10ATM.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "unisex",
        "id": 124,
        "metal": "acero",
        "name": "Reloj Analogico Huawei 16",
        "price": 265.1,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?watch,Huawei,Analogico",
        "watch": "Analogico",
        "watch_bracelet_material": "Nylon",
        "water_resistance": "10ATM",
        "destacado": False,
        "quantity": 53,
    },
    {
        "bracelet": None,
        "brand": "Samsung",
        "caja": "Acero",
        "category": "relojes",
        "clasp": None,
        "coating": "oro rosa 18k",
        "description": "Reloj digital con correa de Nylon y resistencia 10ATM.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "unisex",
        "id": 125,
        "metal": "acero",
        "name": "Reloj Digital Samsung 17",
        "price": 277.9,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?watch,Samsung,Digital",
        "watch": "Digital",
        "watch_bracelet_material": "Nylon",
        "water_resistance": "10ATM",
        "destacado": False,
        "quantity": 56,
    },
    {
        "bracelet": None,
        "brand": "Fossil",
        "caja": "Metal",
        "category": "relojes",
        "clasp": None,
        "coating": None,
        "description": "Reloj smartwatch con correa de Acero y resistencia 5ATM.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "unisex",
        "id": 126,
        "metal": "acero",
        "name": "Reloj SmartWatch Fossil 18",
        "price": 290.0,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?watch,Fossil,SmartWatch",
        "watch": "SmartWatch",
        "watch_bracelet_material": "Acero",
        "water_resistance": "5ATM",
        "destacado": False,
        "quantity": 59,
    },
    {
        "bracelet": None,
        "brand": "Fossil",
        "caja": "Acero",
        "category": "relojes",
        "clasp": None,
        "coating": "oro amarillo 18k",
        "description": "Reloj analogico con correa de Cuero y resistencia 5ATM.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "unisex",
        "id": 127,
        "metal": "acero",
        "name": "Reloj Analogico Fossil 19",
        "price": 302.3,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?watch,Fossil,Analogico",
        "watch": "Analogico",
        "watch_bracelet_material": "Cuero",
        "water_resistance": "5ATM",
        "destacado": False,
        "quantity": 62,
    },
    {
        "bracelet": None,
        "brand": "Huawei",
        "caja": "Acero",
        "category": "relojes",
        "clasp": None,
        "coating": "oro rosa 18k",
        "description": "Reloj analogico con correa de Cuero y resistencia 5ATM.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "unisex",
        "id": 128,
        "metal": "acero",
        "name": "Reloj Analogico Huawei 20",
        "price": 314.8,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?watch,Huawei,Analogico",
        "watch": "Analogico",
        "watch_bracelet_material": "Cuero",
        "water_resistance": "5ATM",
        "destacado": False,
        "quantity": 65,
    },
    {
        "bracelet": None,
        "brand": "Xiaomi",
        "caja": "Acero",
        "category": "relojes",
        "clasp": None,
        "coating": "rodio",
        "description": "Reloj analogico con correa de Silicona y resistencia 3ATM.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "unisex",
        "id": 129,
        "metal": "acero",
        "name": "Reloj Analogico Xiaomi 21",
        "price": 327.1,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?watch,Xiaomi,Analogico",
        "watch": "Analogico",
        "watch_bracelet_material": "Silicona",
        "water_resistance": "3ATM",
        "destacado": False,
        "quantity": 8,
    },
    {
        "bracelet": None,
        "brand": "Huawei",
        "caja": "Acero",
        "category": "relojes",
        "clasp": None,
        "coating": "oro rosa 18k",
        "description": "Reloj analogico con correa de Nylon y resistencia 3ATM.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "unisex",
        "id": 130,
        "metal": "acero",
        "name": "Reloj Analogico Huawei 22",
        "price": 339.6,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?watch,Huawei,Analogico",
        "watch": "Analogico",
        "watch_bracelet_material": "Nylon",
        "water_resistance": "3ATM",
        "destacado": False,
        "quantity": 11,
    },
    {
        "bracelet": None,
        "brand": "Huawei",
        "caja": "Acero",
        "category": "relojes",
        "clasp": None,
        "coating": "oro rosa 18k",
        "description": "Reloj digital con correa de Cuero y resistencia 5ATM.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "unisex",
        "id": 131,
        "metal": "acero",
        "name": "Reloj Digital Huawei 23",
        "price": 351.8,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?watch,Huawei,Digital",
        "watch": "Digital",
        "watch_bracelet_material": "Cuero",
        "water_resistance": "5ATM",
        "destacado": False,
        "quantity": 14,
    },
    {
        "bracelet": None,
        "brand": "Fossil",
        "caja": "Metal",
        "category": "relojes",
        "clasp": None,
        "coating": "rodio",
        "description": "Reloj smartwatch con correa de Acero y resistencia 10ATM.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "unisex",
        "id": 132,
        "metal": "acero",
        "name": "Reloj SmartWatch Fossil 24",
        "price": 364.3,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?watch,Fossil,SmartWatch",
        "watch": "SmartWatch",
        "watch_bracelet_material": "Acero",
        "water_resistance": "10ATM",
        "destacado": False,
        "quantity": 17,
    },
    {
        "bracelet": None,
        "brand": "Samsung",
        "caja": "Acero",
        "category": "relojes",
        "clasp": None,
        "coating": None,
        "description": "Reloj analogico con correa de Acero y resistencia 10ATM.",
        "earring_type": None,
        "gem": "Sin gema",
        "gender": "unisex",
        "id": 133,
        "metal": "acero",
        "name": "Reloj Analogico Samsung 25",
        "price": 376.7,
        "ring_type": None,
        "url_image": "https://source.unsplash.com/featured/?watch,Samsung,Analogico",
        "watch": "Analogico",
        "watch_bracelet_material": "Acero",
        "water_resistance": "10ATM",
        "destacado": False,
        "quantity": 20,
    },
]