products = [
        {
            "bracelet": None,
            "brand": "PDPAOLA",
            "caja": None,
            "category": "anillo",
            "clasp": None,
            "coating": "rodio",
            "description": "Anillo solitario de plata de primera ley con circonita.",
            "earring_type": None,
            "gem": "Circonita",
            "gender": "mujer",
            "id": 8,
            "metal": "plata de primera ley",
            "name": "Anillo solitario plata circonita",
            "price": 49.9,
            "ring_type": "Anillo Solitario",
            "url_image": "https://cdn.palbincdn.com/users/50822/images/12182-anillo-solitario-plata-1698927548-1707780008.jpg",
            "watch": None,
            "watch_bracelet_material": None,
            "water_resistance": None,
            "destacado": False,
            "quantity": 20
        },
        {
            "bracelet": None,
            "brand": "Tous",
            "caja": None,
            "category": "anillo",
            "clasp": None,
            "coating": "oro amarillo 18k",
            "description": "Alianza clásica en oro amarillo de 18k.",
            "earring_type": None,
            "gem": "Sin gema",
            "gender": "mujer",
            "id": 9,
            "metal": "oro amarillo 18k",
            "name": "Anillo alianza oro 18k",
            "price": 299.0,
            "ring_type": "Anillo Alianza",
            "url_image": "https://source.unsplash.com/featured/?gold%20ring",
            "watch": None,
            "watch_bracelet_material": None,
            "water_resistance": None,
            "destacado": False,
            "quantity": 10
        },
        {
            "bracelet": None,
            "brand": "Versace",
            "caja": None,
            "category": "anillo",
            "clasp": None,
            "coating": "rodio",
            "description": "Anillo con gema central esmeralda y baño de rodio.",
            "earring_type": None,
            "gem": "Esmeralda",
            "gender": "mujer",
            "id": 10,
            "metal": "oro blanco 18 k",
            "name": "Anillo con esmeralda oro blanco",
            "price": 599.0,
            "ring_type": "Anillo Con gemas",
            "url_image": "https://source.unsplash.com/featured/?emerald%20ring",
            "watch": None,
            "watch_bracelet_material": None,
            "water_resistance": None,
            "destacado": False,
            "quantity": 5
        },
        {
            "bracelet": None,
            "brand": "Agatha",
            "caja": None,
            "category": "pendientes",
            "clasp": None,
            "coating": "rodio",
            "description": "Pendientes de aro en plata de primera ley.",
            "earring_type": "Pendiente Aro",
            "gem": "Sin gema",
            "gender": "mujer",
            "id": 11,
            "metal": "plata de primera ley",
            "name": "Pendientes aro plata",
            "price": 39.9,
            "ring_type": None,
            "url_image": "https://source.unsplash.com/featured/?silver%20hoop%20earrings",
            "watch": None,
            "watch_bracelet_material": None,
            "water_resistance": None,
            "destacado": False,
            "quantity": 30
        },
        {
            "bracelet": None,
            "brand": "Guess",
            "caja": None,
            "category": "pendientes",
            "clasp": None,
            "coating": "oro rosa 18 k",
            "description": "Pendiente ear cuff en oro rosa de 18k.",
            "earring_type": "Pendiente Ear Cuff",
            "gem": "Sin gema",
            "gender": "mujer",
            "id": 12,
            "metal": "oro rosa 18 k",
            "name": "Ear cuff oro rosa",
            "price": 59.9,
            "ring_type": None,
            "url_image": "https://source.unsplash.com/featured/?ear%20cuff%20rose%20gold",
            "watch": None,
            "watch_bracelet_material": None,
            "water_resistance": None,
            "destacado": False,
            "quantity": 12
        },
        {
            "bracelet": None,
            "brand": "Calvin Klein",
            "caja": None,
            "category": "pendientes",
            "clasp": None,
            "coating": "rodio",
            "description": "Pendientes largos con perla cultivada.",
            "earring_type": "Pendiente Largo",
            "gem": "Perla cultivada",
            "gender": "mujer",
            "id": 13,
            "metal": "plata de primera ley",
            "name": "Pendientes largos perla cultivada",
            "price": 79.0,
            "ring_type": None,
            "url_image": "https://source.unsplash.com/featured/?long%20pearl%20earrings",
            "watch": None,
            "watch_bracelet_material": None,
            "water_resistance": None,
            "destacado": False,
            "quantity": 15
        },
        {
            "bracelet": "Pulsera Bolas",
            "brand": "Viceroy",
            "caja": None,
            "category": "pulseras",
            "clasp": "Ajustable",
            "coating": "rodio",
            "description": "Pulsera de bolas en plata, ajuste fácil.",
            "earring_type": None,
            "gem": "Sin gema",
            "gender": "mujer",
            "id": 14,
            "metal": "plata de primera ley",
            "name": "Pulsera bolas plata",
            "price": 49.9,
            "ring_type": None,
            "url_image": "https://source.unsplash.com/featured/?silver%20bead%20bracelet",
            "watch": None,
            "watch_bracelet_material": None,
            "water_resistance": None,
            "destacado": False,
            "quantity": 25
        },
        {
            "bracelet": "Pulsera Malla",
            "brand": "Tommy Hilfiger",
            "caja": None,
            "category": "pulseras",
            "clasp": "De pulsera",
            "coating": None,
            "description": "Pulsera de malla en acero para look urbano.",
            "earring_type": None,
            "gem": "Sin gema",
            "gender": "hombre",
            "id": 15,
            "metal": "acero",
            "name": "Pulsera malla acero",
            "price": 79.0,
            "ring_type": None,
            "url_image": "https://source.unsplash.com/featured/?stainless%20steel%20mesh%20bracelet",
            "watch": None,
            "watch_bracelet_material": None,
            "water_resistance": None,
            "destacado": False,
            "quantity": 40
        },
        {
            "bracelet": "Pulsera Riviere",
            "brand": "Tous",
            "caja": None,
            "category": "pulseras",
            "clasp": "De pulsera",
            "coating": "rodio",
            "description": "Pulsera riviere con circonitas montadas en plata.",
            "earring_type": None,
            "gem": "Circonita",
            "gender": "mujer",
            "id": 17,
            "metal": "plata de primera ley",
            "name": "Pulsera riviere circonitas",
            "price": 129.0,
            "ring_type": None,
            "url_image": "https://source.unsplash.com/featured/?tennis%20bracelet%20silver",
            "watch": None,
            "watch_bracelet_material": None,
            "water_resistance": None,
            "destacado": False,
            "quantity": 18
        },
        {
            "bracelet": None,
            "brand": "Pandora",
            "caja": None,
            "category": "colgantes",
            "clasp": "Mosqueton",
            "coating": "rodio",
            "description": "Colgante con amatista en plata de primera ley.",
            "earring_type": None,
            "gem": "Amatista",
            "gender": "mujer",
            "id": 18,
            "metal": "plata de primera ley",
            "name": "Colgante amatista plata",
            "price": 89.0,
            "ring_type": None,
            "url_image": "https://source.unsplash.com/featured/?amethyst%20pendant%20silver",
            "watch": None,
            "watch_bracelet_material": None,
            "water_resistance": None,
            "destacado": False,
            "quantity": 22
        },
        {
            "bracelet": None,
            "brand": "Pandora",
            "caja": None,
            "category": "colgantes",
            "clasp": "Mosqueton",
            "coating": "rodio",
            "description": "Colgante con amatista en plata de primera ley.",
            "earring_type": None,
            "gem": "Amatista",
            "gender": "mujer",
            "id": 19,
            "metal": "plata de primera ley",
            "name": "Colgante amatista plata",
            "price": 89.0,
            "ring_type": None,
            "url_image": "https://source.unsplash.com/featured/?amethyst%20pendant%20silver",
            "watch": None,
            "watch_bracelet_material": None,
            "water_resistance": None,
            "destacado": False,
            "quantity": 20
        },
        {
            "bracelet": None,
            "brand": "Seiko",
            "caja": "Acero",
            "category": "relojes",
            "clasp": None,
            "coating": None,
            "description": "Reloj analógico de acero con resistencia 5ATM.",
            "earring_type": None,
            "gem": "Sin gema",
            "gender": "hombre",
            "id": 20,
            "metal": "acero",
            "name": "Reloj analógico acero 5ATM",
            "price": 199.0,
            "ring_type": None,
            "url_image": "https://source.unsplash.com/featured/?stainless%20steel%20analog%20watch",
            "watch": "Analogico",
            "watch_bracelet_material": "Acero",
            "water_resistance": "5ATM",
            "destacado": False,
            "quantity": 8
        },
        {
            "bracelet": None,
            "brand": "Casio",
            "caja": "Resina",
            "category": "relojes",
            "clasp": None,
            "coating": None,
            "description": "Reloj digital deportivo, caja de resina, 10ATM.",
            "earring_type": None,
            "gem": "Sin gema",
            "gender": "unisex",
            "id": 21,
            "metal": "acero",
            "name": "Reloj digital resina 10ATM",
            "price": 49.0,
            "ring_type": None,
            "url_image": "https://source.unsplash.com/featured/?digital%20sports%20watch",
            "watch": "Digital",
            "watch_bracelet_material": "Nylon",
            "water_resistance": "10ATM",
            "destacado": False,
            "quantity": 50
        },
        {
            "bracelet": None,
            "brand": "Mark Maddox",
            "caja": "Metal",
            "category": "relojes",
            "clasp": None,
            "coating": None,
            "description": "SmartWatch con caja metálica y correa de nylon.",
            "earring_type": None,
            "gem": "Sin gema",
            "gender": "unisex",
            "id": 22,
            "metal": "acero",
            "name": "SmartWatch metal nylon",
            "price": 129.0,
            "ring_type": None,
            "url_image": "https://source.unsplash.com/featured/?smartwatch%20nylon%20band",
            "watch": "SmartWatch",
            "watch_bracelet_material": "Nylon",
            "water_resistance": "3ATM",
            "destacado": False,
            "quantity": 35
        }
    ]
