"""empty message

Revision ID: 3166d7c1da11
Revises: 
Create Date: 2025-09-29 10:01:11.067359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3166d7c1da11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bracelet_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bracelet_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bracelet_types_name'), ['name'], unique=True)

    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brands_name'), ['name'], unique=True)

    op.create_table('caja_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('caja_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_caja_types_name'), ['name'], unique=True)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=True)

    op.create_table('clasps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clasps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clasps_name'), ['name'], unique=True)

    op.create_table('coatings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coatings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coatings_name'), ['name'], unique=True)

    op.create_table('earring_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('earring_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_earring_types_name'), ['name'], unique=True)

    op.create_table('gems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gems_name'), ['name'], unique=True)

    op.create_table('genders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('genders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_genders_name'), ['name'], unique=True)

    op.create_table('jewells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('url_image', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('coating', sa.String(length=30), nullable=True),
    sa.Column('brand', sa.String(length=30), nullable=True),
    sa.Column('gender', sa.String(length=30), nullable=True),
    sa.Column('clasp', sa.String(length=30), nullable=True),
    sa.Column('water_resistance', sa.String(length=30), nullable=True),
    sa.Column('caja', sa.String(length=30), nullable=True),
    sa.Column('metal', sa.String(length=30), nullable=True),
    sa.Column('gem', sa.String(length=30), nullable=True),
    sa.Column('ring_type', sa.String(length=30), nullable=True),
    sa.Column('earring_type', sa.String(length=30), nullable=True),
    sa.Column('bracelet', sa.String(length=30), nullable=True),
    sa.Column('watch', sa.String(length=30), nullable=True),
    sa.Column('watch_bracelet_material', sa.String(length=30), nullable=True),
    sa.Column('highlighted', sa.Boolean(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metals_name'), ['name'], unique=True)

    op.create_table('ring_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ring_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ring_types_name'), ['name'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('watch_bracelet_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watch_bracelet_materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watch_bracelet_materials_name'), ['name'], unique=True)

    op.create_table('watch_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watch_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watch_types_name'), ['name'], unique=True)

    op.create_table('water_resistances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('water_resistances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_water_resistances_name'), ['name'], unique=True)

    op.create_table('discount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('discount_code', sa.String(length=20), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jewell_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jewell_id'], ['jewells.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'jewell_id')
    )
    op.create_table('shoppingcart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jewell_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jewell_id'], ['jewells.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_direction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_address', sa.String(length=120), nullable=False),
    sa.Column('second_address', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=20), nullable=False),
    sa.Column('province', sa.String(length=40), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('discount_id', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['discount_id'], ['discount.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('jewell_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jewell_id'], ['jewells.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale_items')
    op.drop_table('sales')
    op.drop_table('user_direction')
    op.drop_table('shoppingcart')
    op.drop_table('favorites')
    op.drop_table('discount')
    with op.batch_alter_table('water_resistances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_water_resistances_name'))

    op.drop_table('water_resistances')
    with op.batch_alter_table('watch_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watch_types_name'))

    op.drop_table('watch_types')
    with op.batch_alter_table('watch_bracelet_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watch_bracelet_materials_name'))

    op.drop_table('watch_bracelet_materials')
    op.drop_table('user')
    with op.batch_alter_table('ring_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ring_types_name'))

    op.drop_table('ring_types')
    with op.batch_alter_table('metals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metals_name'))

    op.drop_table('metals')
    op.drop_table('jewells')
    with op.batch_alter_table('genders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genders_name'))

    op.drop_table('genders')
    with op.batch_alter_table('gems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gems_name'))

    op.drop_table('gems')
    with op.batch_alter_table('earring_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_earring_types_name'))

    op.drop_table('earring_types')
    with op.batch_alter_table('coatings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coatings_name'))

    op.drop_table('coatings')
    with op.batch_alter_table('clasps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clasps_name'))

    op.drop_table('clasps')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_name'))

    op.drop_table('categories')
    with op.batch_alter_table('caja_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_caja_types_name'))

    op.drop_table('caja_types')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brands_name'))

    op.drop_table('brands')
    with op.batch_alter_table('bracelet_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bracelet_types_name'))

    op.drop_table('bracelet_types')
    # ### end Alembic commands ###
