export const catalogo = {
  ok: true,
  total: 14,
  items: [
    {
      "bracelet": null,
      "brand": "PDPAOLA",
      "caja": null,
      "category": "anillo",
      "clasp": null,
      "coating": "rodio",
      "description": "Anillo solitario de plata de primera ley con circonita.",
      "earring_type": null,
      "gem": "Circonita",
      "gender": "mujer",
      "id": 8,
      "metal": "plata de primera ley",
      "name": "Anillo solitario plata circonita",
      "price": 49.9,
      "ring_type": "Anillo Solitario",
      "url_image": "https://cdn.palbincdn.com/users/50822/images/12182-anillo-solitario-plata-1698927548-1707780008.jpg",
      "watch": null,
      "watch_bracelet_material": null,
      "water_resistance": null,
      "destacado": false
    },
    {
      "bracelet": null,
      "brand": "Tous",
      "caja": null,
      "category": "anillo",
      "clasp": null,
      "coating": "oro amarillo 18k",
      "description": "Alianza clásica en oro amarillo de 18k.",
      "earring_type": null,
      "gem": "Sin gema",
      "gender": "mujer",
      "id": 9,
      "metal": "oro amarillo 18k",
      "name": "Anillo alianza oro 18k",
      "price": 299.0,
      "ring_type": "Anillo Alianza",
      "url_image": "https://source.unsplash.com/featured/?gold%20ring",
      "watch": null,
      "watch_bracelet_material": null,
      "water_resistance": null,
      "destacado": false
    },
    {
      "bracelet": null,
      "brand": "Versace",
      "caja": null,
      "category": "anillo",
      "clasp": null,
      "coating": "rodio",
      "description": "Anillo con gema central esmeralda y baño de rodio.",
      "earring_type": null,
      "gem": "Esmeralda",
      "gender": "mujer",
      "id": 10,
      "metal": "oro blanco 18 k",
      "name": "Anillo con esmeralda oro blanco",
      "price": 599.0,
      "ring_type": "Anillo Con gemas",
      "url_image": "https://source.unsplash.com/featured/?emerald%20ring",
      "watch": null,
      "watch_bracelet_material": null,
      "water_resistance": null,
      "destacado": false
    },
    {
      "bracelet": null,
      "brand": "Agatha",
      "caja": null,
      "category": "pendientes",
      "clasp": null,
      "coating": "rodio",
      "description": "Pendientes de aro en plata de primera ley.",
      "earring_type": "Pendiente Aro",
      "gem": "Sin gema",
      "gender": "mujer",
      "id": 11,
      "metal": "plata de primera ley",
      "name": "Pendientes aro plata",
      "price": 39.9,
      "ring_type": null,
      "url_image": "https://source.unsplash.com/featured/?silver%20hoop%20earrings",
      "watch": null,
      "watch_bracelet_material": null,
      "water_resistance": null,
      "destacado": false
    },
    {
      "bracelet": null,
      "brand": "Guess",
      "caja": null,
      "category": "pendientes",
      "clasp": null,
      "coating": "oro rosa 18 k",
      "description": "Pendiente ear cuff en oro rosa de 18k.",
      "earring_type": "Pendiente Ear Cuff",
      "gem": "Sin gema",
      "gender": "mujer",
      "id": 12,
      "metal": "oro rosa 18 k",
      "name": "Ear cuff oro rosa",
      "price": 59.9,
      "ring_type": null,
      "url_image": "https://source.unsplash.com/featured/?ear%20cuff%20rose%20gold",
      "watch": null,
      "watch_bracelet_material": null,
      "water_resistance": null,
      "destacado": false
    },
    {
      "bracelet": null,
      "brand": "Calvin Klein",
      "caja": null,
      "category": "pendientes",
      "clasp": null,
      "coating": "rodio",
      "description": "Pendientes largos con perla cultivada.",
      "earring_type": "Pendiente Largo",
      "gem": "Perla cultivada",
      "gender": "mujer",
      "id": 13,
      "metal": "plata de primera ley",
      "name": "Pendientes largos perla cultivada",
      "price": 79.0,
      "ring_type": null,
      "url_image": "https://source.unsplash.com/featured/?long%20pearl%20earrings",
      "watch": null,
      "watch_bracelet_material": null,
      "water_resistance": null,
      "destacado": false
    },
    {
      "bracelet": "Pulsera Bolas",
      "brand": "Viceroy",
      "caja": null,
      "category": "pulseras",
      "clasp": "Ajustable",
      "coating": "rodio",
      "description": "Pulsera de bolas en plata, ajuste fácil.",
      "earring_type": null,
      "gem": "Sin gema",
      "gender": "mujer",
      "id": 14,
      "metal": "plata de primera ley",
      "name": "Pulsera bolas plata",
      "price": 49.9,
      "ring_type": null,
      "url_image": "https://source.unsplash.com/featured/?silver%20bead%20bracelet",
      "watch": null,
      "watch_bracelet_material": null,
      "water_resistance": null,
      "destacado": false
    },
    {
      "bracelet": "Pulsera Malla",
      "brand": "Tommy Hilfiger",
      "caja": null,
      "category": "pulseras",
      "clasp": "De pulsera",
      "coating": null,
      "description": "Pulsera de malla en acero para look urbano.",
      "earring_type": null,
      "gem": "Sin gema",
      "gender": "hombre",
      "id": 15,
      "metal": "acero",
      "name": "Pulsera malla acero",
      "price": 79.0,
      "ring_type": null,
      "url_image": "https://source.unsplash.com/featured/?stainless%20steel%20mesh%20bracelet",
      "watch": null,
      "watch_bracelet_material": null,
      "water_resistance": null,
      "destacado": false
    },
    {
      "bracelet": "Pulsera Riviere",
      "brand": "Tous",
      "caja": null,
      "category": "pulseras",
      "clasp": "De pulsera",
      "coating": "rodio",
      "description": "Pulsera riviere con circonitas montadas en plata.",
      "earring_type": null,
      "gem": "Circonita",
      "gender": "mujer",
      "id": 17,
      "metal": "plata de primera ley",
      "name": "Pulsera riviere circonitas",
      "price": 129.0,
      "ring_type": null,
      "url_image": "https://source.unsplash.com/featured/?tennis%20bracelet%20silver",
      "watch": null,
      "watch_bracelet_material": null,
      "water_resistance": null,
      "destacado": false
    },
    {
      "bracelet": null,
      "brand": "Pandora",
      "caja": null,
      "category": "colgantes",
      "clasp": "Mosqueton",
      "coating": "rodio",
      "description": "Colgante con amatista en plata de primera ley.",
      "earring_type": null,
      "gem": "Amatista",
      "gender": "mujer",
      "id": 18,
      "metal": "plata de primera ley",
      "name": "Colgante amatista plata",
      "price": 89.0,
      "ring_type": null,
      "url_image": "https://source.unsplash.com/featured/?amethyst%20pendant%20silver",
      "watch": null,
      "watch_bracelet_material": null,
      "water_resistance": null,
      "destacado": false
    },
    {
      "bracelet": null,
      "brand": "Pandora",
      "caja": null,
      "category": "colgantes",
      "clasp": "Mosqueton",
      "coating": "rodio",
      "description": "Colgante con amatista en plata de primera ley.",
      "earring_type": null,
      "gem": "Amatista",
      "gender": "mujer",
      "id": 19,
      "metal": "plata de primera ley",
      "name": "Colgante amatista plata",
      "price": 89.0,
      "ring_type": null,
      "url_image": "https://source.unsplash.com/featured/?amethyst%20pendant%20silver",
      "watch": null,
      "watch_bracelet_material": null,
      "water_resistance": null,
      "destacado": false
    },
    {
      "bracelet": null,
      "brand": "Seiko",
      "caja": "Acero",
      "category": "relojes",
      "clasp": null,
      "coating": null,
      "description": "Reloj analógico de acero con resistencia 5ATM.",
      "earring_type": null,
      "gem": "Sin gema",
      "gender": "hombre",
      "id": 20,
      "metal": "acero",
      "name": "Reloj analógico acero 5ATM",
      "price": 199.0,
      "ring_type": null,
      "url_image": "https://source.unsplash.com/featured/?stainless%20steel%20analog%20watch",
      "watch": "Analogico",
      "watch_bracelet_material": "Acero",
      "water_resistance": "5ATM",
      "destacado": false
    },
    {
      "bracelet": null,
      "brand": "Casio",
      "caja": "Resina",
      "category": "relojes",
      "clasp": null,
      "coating": null,
      "description": "Reloj digital deportivo, caja de resina, 10ATM.",
      "earring_type": null,
      "gem": "Sin gema",
      "gender": "unisex",
      "id": 21,
      "metal": "acero",
      "name": "Reloj digital resina 10ATM",
      "price": 49.0,
      "ring_type": null,
      "url_image": "https://source.unsplash.com/featured/?digital%20sports%20watch",
      "watch": "Digital",
      "watch_bracelet_material": "Nylon",
      "water_resistance": "10ATM",
      "destacado": false
    },
    {
      "bracelet": null,
      "brand": "Mark Maddox",
      "caja": "Metal",
      "category": "relojes",
      "clasp": null,
      "coating": null,
      "description": "SmartWatch con caja metálica y correa de nylon.",
      "earring_type": null,
      "gem": "Sin gema",
      "gender": "unisex",
      "id": 22,
      "metal": "acero",
      "name": "SmartWatch metal nylon",
      "price": 129.0,
      "ring_type": null,
      "url_image": "https://source.unsplash.com/featured/?smartwatch%20nylon%20band",
      "watch": "SmartWatch",
      "watch_bracelet_material": "Nylon",
      "water_resistance": "3ATM",
      "destacado": false
    }
  ]
}
